### PR TITLE
Home Panel v2 addon upgrade

### LINKED ISSUE #21: Socket connection timed out
# Problem/Motivation
hassio 0.92.2, with home panel addon 0.4.1, Socket connection timed out
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
new installation
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

### LINKED ISSUE #24: Cannot make a account
i'm using hass.io, i've installed the addon en started it and the log looks fine:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Home Panel
 A touch-compatible web frontend for controlling the home
-----------------------------------------------------------
 Add-on version: 0.4.1
 You are running the latest version of this add-on.
 System: HassOS 2.12  (amd64 / qemux86-64)
 Home Assistant version: 0.95.4
 Supervisor version: 169
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] secrets.sh: executing... 
[cont-init.d] secrets.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:17:29] INFO: Run API..
info: API started on https://localhost:3234
[16:17:31] INFO: Starting NGINX...

If i make a account is doesn't load further and then the log says this:

[18/Jul/2019:16:20:18 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:18 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/css/2.79e61001.chunk.css HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:18 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/js/2.4394ac3a.chunk.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:18 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/css/main.233fda59.chunk.css HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:18 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/js/main.580669db.chunk.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:20 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/logo.7d2d127a.svg HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:20 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-400.5d4aeb4e.woff2 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:20 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-500.28546717.woff2 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:20 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /service-worker.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /precache-manifest.aa095b593d45ea60a563678dad495c88.js HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /index.html?__WB_REVISION__=a189729b068d81ef0f9536c380ea2f39 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/css/2.79e61001.chunk.css?__WB_REVISION__=64ea0537589877056a01 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/css/main.233fda59.chunk.css?__WB_REVISION__=566f1652b4ced5ef1907 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/logo.7d2d127a.svg?__WB_REVISION__=7d2d127ab1a85dcaec56c148ae2e25d7 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/js/runtime~main.2c977d9b.js?__WB_REVISION__=9eb600ee07a27cdad64f HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/js/main.580669db.chunk.js?__WB_REVISION__=566f1652b4ced5ef1907 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/js/2.4394ac3a.chunk.js?__WB_REVISION__=64ea0537589877056a01 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/materialdesignicons-webfont.1a95531b.woff?__WB_REVISION__=1a95531b09ffc9b76104e0003b456a0e HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-100italic.d704bb3d.woff?__WB_REVISION__=d704bb3d579b7d5e40880c75705c8a71 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/materialdesignicons-webfont.84c6fe1e.woff2?__WB_REVISION__=84c6fe1e4353c916d8f1452e82bdef8d HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-300.55536c8e.woff2?__WB_REVISION__=55536c8e9e9a532651e3cf374f290ea3 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-100.987b8457.woff2?__WB_REVISION__=987b84570ea69ee660455b8d5e91f5f1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-100.e9dbbe8a.woff?__WB_REVISION__=e9dbbe8a693dd275c16d32feb101f1c1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-100italic.6232f43d.woff2?__WB_REVISION__=6232f43d15b0e7a0bf0fe82e295bdd06 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/materialdesignicons-webfont.6acc7d6c.ttf?__WB_REVISION__=6acc7d6cffa21f6eda4baaa90e835fd2 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-400.5d4aeb4e.woff2?__WB_REVISION__=5d4aeb4e5f5ef754e307d7ffaef688bd HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-300italic.210a7c78.woff?__WB_REVISION__=210a7c781f5a354a0e4985656ab456d9 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-300.a1471d1d.woff?__WB_REVISION__=a1471d1d6431c893582a5f6a250db3f9 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-300italic.d69924b9.woff2?__WB_REVISION__=d69924b98acd849cdeba9fbff3f88ea6 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-400.bafb105b.woff?__WB_REVISION__=bafb105baeb22d965c70fe52ba6b49d9 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-400italic.9680d5a0.woff?__WB_REVISION__=9680d5a0c32d2fd084e07bbc4c8b2923 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-400italic.d8bcbe72.woff2?__WB_REVISION__=d8bcbe724fd6f4ba44d0ee6a2675890f HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-500.28546717.woff2?__WB_REVISION__=285467176f7fe6bb6a9c6873b3dad2cc HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-500.de8b7431.woff?__WB_REVISION__=de8b7431b74642e830af4d4f4b513ec9 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-500italic.510dec37.woff2?__WB_REVISION__=510dec37fa69fba39593e01a469ee018 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-500italic.ffcc050b.woff?__WB_REVISION__=ffcc050b2d92d4b14a4fcb527ee0bcc8 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-700.037d8304.woff2?__WB_REVISION__=037d830416495def72b7881024c14b7b HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-700.cf6613d1.woff?__WB_REVISION__=cf6613d1adf490972c557a8e318e0868 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-700italic.010c1aee.woff2?__WB_REVISION__=010c1aeee3c6d1cbb1d5761d80353823 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-700italic.846d1890.woff?__WB_REVISION__=846d1890aee87fde5d8ced8eba360c3a HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-900.19b7a0ad.woff2?__WB_REVISION__=19b7a0adfdd4f808b53af7e2ce2ad4e5 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-900.8c2ade50.woff?__WB_REVISION__=8c2ade503b34e31430d6c98aa29a52a3 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-900italic.7b770d6c.woff2?__WB_REVISION__=7b770d6c53423deb1a8e49d3c9175184 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/materialdesignicons-webfont.be7691c1.eot?__WB_REVISION__=be7691c114e7c9d0543b89e824c4003d HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/roboto-latin-900italic.bc833e72.woff?__WB_REVISION__=bc833e725c137257c2c42a789845d82f HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)
[18/Jul/2019:16:20:21 +0200] 200 ::ffff:193.173.218.48, 172.30.33.4, 172.30.32.1(172.30.32.2) GET /static/media/materialdesignicons-webfont.c68a0a65.svg?__WB_REVISION__=c68a0a65b3a0be718f4c81c02c5f69ca HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36)

### PR DESCRIPTION
**Pull request by timmo001**
# Proposed Changes

This is a rewrite of the addon, specifically to expose one port, so ingress will work without having to expose another port to the outside world and to work with nabu casa.

**Do not merge until next release of Home Panel and TODOs have been resolved** Changes have been made on to the app which will allow relative paths. There are likely more to come

### CODE REVIEW

File: home-panel/rootfs/etc/services.d/nginx/run [hunk 1]
```diff
@@ -1,15 +1,12 @@
...
+# Runs the Nginx daemon
 # ==============================================================================
-# Wait for the API to start
-bashio::net.wait_for 3234
 
-# Disable HA Authentication if front door is open
-if bashio::config.true 'leave_front_door_open'; then
-    export DISABLE_HA_AUTHENTICATION=true
-fi
+# Wait for thelounge to become available
```
Comment (frenck) [inline home-panel/rootfs/etc/services.d/nginx/run]:
```suggestion
# Wait for Home Panel to become available
```
